### PR TITLE
* Fix repeated insertion problem when the value is the same. (e.g. Re…

### PR DESCRIPTION
**Pull request by MESOLONELY**
e.g. Remote changes [2, 1], localAfter [2, 3, 4], [2] will repeated insertion once, become [2, 2, 1, 3, 4]

### CODE REVIEW

**Comment by Anduin2017** [comment]
Restart pull request to trigger a build.

**Review by Anduin2017 — APPROVED** [review]
Nicely done!

**Comment by Anduin2017** [comment]
Could you please write a new unit test which covers your case, so the same issue won't happen again? And I will merge this. Thanks!

It's really well done.

**Comment by MESOLONELY** [comment]
Sure! Will do

**Comment by MESOLONELY** [comment]
Just returned to my laptop, I found it I seems haven't fully solved it. I'll make some further changes.

**Review by Anduin2017 — CHANGES_REQUESTED** [review]
Pending for unit test.

**Pull request closed without merging**
